export const siteData = {
  personal: {
    name: "Naeem Ur Rahman",
    role: "Full-Stack Engineer & AI Developer",
    bio: "Final-year Computer Science student and software engineer specializing in scalable full-stack architectures and production-ready AI/ML systems. I build complex SaaS platforms and integrate intelligent data pipelines to solve real-world clinical and business problems.",
    email: "naeem.riu.32@gmail.com",
    whatsapp: "+923193625232",
    whatsappDisplay: "+92 319 362 5232",
    github: "https://github.com/Rehman32",
    linkedin: "https://linkedin.com/in/naeem-ur-rahman-641b3a276",
    location: "Islamabad, Pakistan",
    locationFlag: "🇵🇰",
    availability: "Available for Opportunities",
    availabilityStatus: "open",
    responseTime: "Usually responds within 24h",
    photo: "/dp.jpg",
  },
  experience: [
    {
      title: "Software Engineering Intern",
      company: "Software Productivity Strategists, Inc. (SPS)",
      companyShort: "SPS Inc.",
      date: "Aug 2024 – Present",
      type: "Internship",
      tracks: ["Full-Stack Development", "AI Integration", "DevOps"],
      description:
        "Working across three core tracks: Full-Stack Development, AI Integration, and DevOps. Architecting scalable solutions and integrating machine learning models into production workflows.",
    },
    {
      title: "Freelance Full-Stack Developer",
      company: "Independent",
      companyShort: "Freelance",
      date: "2023 – Present",
      type: "Freelance",
      tracks: ["SaaS Platforms", "UI/UX", "Cloud Deployment"],
      description:
        "Designed and deployed custom, industry-grade SaaS platforms including School Management Systems and online learning portals, managing the complete lifecycle from UI/UX to cloud deployment.",
    },
  ],
  education: {
    degree: "BS Computer Science",
    institution: "Riphah International University, Islamabad",
    institutionShort: "Riphah International University",
    graduation: "Expected 2026",
    cgpa: "3.7",
    cgpaMax: "4.0",
  },
  skills: {
    frontend: ["Next.js", "React 19", "TypeScript", "Tailwind CSS","Shadcn UI", "Zustand"],
    backend: ["Node.js", "FastAPI", "Express.js","TypeScript", "PostgreSQL", "MongoDB","MySQL"],
    ai_ml: ["Python", "TensorFlow", "LangChain", "RAG", "Medical AI", "Computer Vision","NLP","PyTorch"],
    devops: ["Docker", "Kubernetes", "GitHub Actions", "AWS EC2", "AWS S3", "AWS Lambda", "Firebase", "Linux / Bash", "CI/CD Pipelines"],
  },
  projects: [
    {
      title: "OncoVisionX",
      subtitle: "Medical AI · Clinical Decision Support",
      status: "Deployed",
      featured: true,
      priority: 1,
      description:
        "Enterprise Clinical Decision Support System for multimodal skin cancer triage. Architected a custom inference pipeline using ConvNeXt-Tiny and FAISS for out-of-distribution detection, wrapped in an asynchronous FastAPI backend and a Next.js clinical UI.",
      techStack: ["Next.js", "FastAPI", "Python", "TensorFlow", "Medical AI"],
      githubUrl: "https://github.com/Rehman32/OncoVisionX",
      liveUrl: "https://github.com/Rehman32",
      accentColor: "violet",
      gridSpan: "col-span-7",
    },
    {
      title: "ContractLens",
      subtitle: "Legal SaaS · AI Contract Intelligence",
      status: "Deployed",
      featured: true,
      priority: 2,
      description:
        "AI-powered contract intelligence platform. Engineered a production-grade RAG pipeline using LangChain and ChromaDB for semantic search over legal PDFs, featuring structured JSON output parsing for clause-level risk analysis.",
      techStack: ["Next.js 14", "FastAPI", "PostgreSQL", "ChromaDB", "OpenAI"],
      githubUrl: "https://github.com/Rehman32/ContractLens.git",
      liveUrl: "https://github.com/Rehman32",
      accentColor: "sky",
      gridSpan: "col-span-5",
    },
    {
      title: "SharpEduManage",
      subtitle: "Enterprise SaaS · School Management",
      status: "Deployed",
      featured: false,
      priority: 3,
      description:
        "Industry-grade School Management System digitizing administrative operations. Implemented complex linked-data architecture for automated timetables, custom JWT auth with rotating tokens, and Excel data export.",
      techStack: ["React 19", "Node.js", "Express", "MongoDB", "Tailwind 4"],
      githubUrl: "https://github.com/Rehman32/school-management-mern-client",
      liveUrl: "https://sharpedumanage.vercel.app/login",
      accentColor: "emerald",
      gridSpan: "col-span-4",
    },
    {
      title: "FlavorAI",
      subtitle: "Full-Stack · AI Culinary Platform",
      status: "Deployed",
      featured: false,
      priority: 4,
      description:
        "AI-driven culinary platform bridging recipe discovery with health analytics. Architected global state management with Zustand/TanStack Query and integrated the Spoonacular API handling 500k+ recipes.",
      techStack: ["React 19", "TypeScript", "Node.js", "MongoDB", "Zustand"],
      githubUrl: "https://github.com/Rehman32/food-recipe-mern-app",
      liveUrl: "https://flavorai-sigma.vercel.app/",
      accentColor: "amber",
      gridSpan: "col-span-4",
    },
    {
      title: "Taleem-ul-Quran",
      subtitle: "E-Learning · Online Academy",
      status: "Deployed",
      featured: false,
      priority: 5,
      description:
        "Custom online academy platform facilitating remote learning. Built complete user interfaces and backend APIs to handle student enrollment and structured content delivery at scale.",
      techStack: ["React", "Node.js", "Express", "MongoDB"],
      githubUrl: "https://github.com/Rehman32/TaleemUlQuran",
      liveUrl: "https://taleem-ul-quran-online-quran-academy.vercel.app/",
      accentColor: "teal",
      gridSpan: "col-span-4",
    },
  ],
  contact: {
    headline: "Let's Build Something",
    headlineAccent: "Remarkable.",
    subtext: "Open to full-time roles, freelance collaborations, and research partnerships. I reply fast.",
    cta: "Send an Email",
  },
  marqueeItems: [
    "Next.js 14", "FastAPI", "TensorFlow", "LangChain", "RAG Pipelines",
    "PostgreSQL", "Docker", "TypeScript", "ConvNeXt-Tiny", "FAISS",
    "ChromaDB", "Kubernetes", "Python", "Medical AI", "Computer Vision",
  ],
  obsessing: [
    "ConvNeXt-Tiny", "FAISS", "RAG Pipelines", "ChromaDB",
    "LangChain", "FastAPI", "Kubernetes", "Medical AI",
  ],
  stats: [
    { label: "Projects Shipped", value: "5+", suffix: "" },
    { label: "Months Experience", value: "18+", suffix: "" },
    { label: "GPA", value: "3.7", suffix: "/4.0" },
    { label: "Recipes Handled", value: "500k", suffix: "+" },
  ],
};
